force-app/main/default/objects/ErrorLog__c/ErrorLog__c.object-meta.xml
<CustomObject>
    <description>Internal object. Information when an unexpected error occurs.</description>

    <label>MBC Error Log</label>
    <nameField>
        <displayFormat>EL-{0000}</displayFormat>
        <label>MBC Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MBC Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ErrorLog__c/fields/LineNumber__c.field-meta.xml
<CustomField>
    <fullName>LineNumber__c</fullName>
    <description>Line number where an error occurs.</description>
    <inlineHelpText>Line number where an error occurs.</inlineHelpText>
    <label>Line Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Error message.</description>
    <inlineHelpText>Error message.</inlineHelpText>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <description>A list of the method calls when an application exception occurs.</description>
    <inlineHelpText>A list of the method calls when an application exception occurs.</inlineHelpText>
    <label>Stack Trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Exception type that generated the error.</description>
    <inlineHelpText>Exception type that generated the error.</inlineHelpText>
    <label>Type</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <description>ID of the user.</description>
    <inlineHelpText>ID of the User.</inlineHelpText>
    <label>User ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FailedMembers__c/FailedMembers__c.object-meta.xml
<CustomObject>
    <label>Failed Member</label>
    <nameField>
        <displayFormat>MBS-{0000000000}</displayFormat>
        <label>Member Balance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Failed Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FailedMembers__c/fields/Member__c.field-meta.xml
<CustomField>
    <fullName>Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Member</label>
    <referenceTo>FieloPLT__Member__c</referenceTo>
    <relationshipLabel>Failed Members</relationshipLabel>
    <relationshipName>FailedMembers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MBCFailedRecord__e/MBCFailedRecord__e.object-meta.xml
<CustomObject>
    <label>Failed Record</label>
    <pluralLabel>Failed Records</pluralLabel>
</CustomObject>

force-app/main/default/classes/MBCService.cls
public class MBCService {

    public static void failedRecords(Set<Id> recordIds, String message) {
        MBCFailedRecord__e payload = new MBCFailedRecord__e(
            Payload__c = String.join(new List<Id>(recordIds), ','),
            Message__c = message
        );
        // Call method to publish events
        Database.SaveResult result = EventBus.publish(payload);

        // Inspect publishing result for each event
        if (!result.isSuccess()) {
            insertErrors(result.getErrors());
        }
    }

    public static void insertErrors(List<Database.Error> errors){
        List<ErrorLog__c> errorList = new List<ErrorLog__c>();
        for (Database.Error e : errors) {
            errorList.add(
                new ErrorLog__c(
                    Message__c = e.getStatusCode() + ' ' + e.getMessage(),
                    Type__c = 'Database.Error',
                    UserId__c = UserInfo.getUserId()
                )
            );
        }
        insert errorList;
    }

    public static void insertError(Exception except){
        insert new ErrorLog__c(
            LineNumber__c = except.getLineNumber(),
            Message__c = except.getMessage(),
            StackTrace__c = except.getStackTraceString(),
            Type__c = except.getTypeName(),
            UserId__c = UserInfo.getUserId()
        );
    }

    public static void processEvents(List<MBCFailedRecord__e> mbcFailedRecords) {
        List<FailedMembers__c> records = new List<FailedMembers__c>();

        for (MBCFailedRecord__e event : mbcFailedRecords) {
            if(String.isNotBlank(event.Payload__c)) {
                for(String memberId : event.Payload__c.split(',')) {
                    records.add(
                        new FailedMembers__c(
                            Member__c = memberId,
                            Message__c = event.Message__c
                        )
                    );
                }
            }
        }

        insert records;
    }
}